# Generated by Django 4.1.3 on 2022-12-02 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_userprofile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
    ]
