# Generated by Django 4.1.1 on 2022-11-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_question_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='questions',
        ),
    ]
